# SSL
server.ssl.enabled=true
server.ssl.key-store=${BFF_WEB_SSL_KEYSTORE_PATH:file:/app/keystore.p12}
server.ssl.key-store-password=${BFF_ATM_SSL_KEYSTORE_PASSWORD}
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=bff-atm

spring.security.oauth2.resourceserver.jwt.issuer-uri=${AUTH_SERVER_ISSUER:http://localhost:9000}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${AUTH_SERVER_JWK_URI:http://localhost:9000/oauth2/jwks}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
