name: Deploy Bank XYZ to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Configurar clave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2.pem
          chmod 600 ~/.ssh/ec2.pem

      - name: Desplegar en EC2
        run: |
          ssh -o StrictHostKeyChecking=no \
            -i ~/.ssh/ec2.pem \
            "${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}" << EOF

            set -e

            if [ ! -d "\$HOME/bankxyz" ]; then
              git clone https://github.com/MiguelZananiri/Bank-XYZ-EFT.git "\$HOME/bankxyz"
            else
              cd "\$HOME/bankxyz"
              git pull
            fi

            cd "\$HOME/bankxyz"

            printf '%s\n' \
              'BANKXYZ_DB_PASSWORD=${{ secrets.BANKXYZ_DB_PASSWORD }}' \
              'AUTH_WEB_CLIENT_SECRET=${{ secrets.AUTH_WEB_CLIENT_SECRET }}' \
              'AUTH_MOBILE_CLIENT_SECRET=${{ secrets.AUTH_MOBILE_CLIENT_SECRET }}' \
              'AUTH_ATM_CLIENT_SECRET=${{ secrets.AUTH_ATM_CLIENT_SECRET }}' \
              'BFF_WEB_SSL_KEYSTORE_PASSWORD=${{ secrets.BFF_WEB_SSL_KEYSTORE_PASSWORD }}' \
              'BFF_MOBILE_SSL_KEYSTORE_PASSWORD=${{ secrets.BFF_MOBILE_SSL_KEYSTORE_PASSWORD }}' \
              'BFF_ATM_SSL_KEYSTORE_PASSWORD=${{ secrets.BFF_ATM_SSL_KEYSTORE_PASSWORD }}' \
              'EC2_HOST=${{ secrets.EC2_HOST }}' \
              > .env

            chmod 600 .env

            docker compose config > /dev/null

            docker compose build

          EOF
