name: Deploy Bank XYZ to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configurar clave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2.pem
          chmod 600 ~/.ssh/ec2.pem

      - name: Desplegar en EC2
        run: |
          ssh -o StrictHostKeyChecking=no \
            -i ~/.ssh/ec2.pem \
            "${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}" << 'EOF'

            if [ ! -d "$HOME/bankxyz" ]; then
              git clone TU_URL_DEL_REPOSITORIO "$HOME/bankxyz"
            else
              cd "$HOME/bankxyz"
              git pull
            fi

            cd "$HOME/bankxyz"

            docker compose build

          EOF
